## Some data cleaning: lobbying

We now tidy up the lobbying data. Here are a few of the initial goals:
1. Identify which lobbying reports are relevant, and which we should remove from our consideration.
2. Column hygiene: remove unnecessary columns so as to de-clutter, and break up columns that contain dictionaries into individual columns.
3. Row hygiene: identify and drop duplicate filings.
4. Incorporate information from amendment filings into the original filings they amended, so that amendments can be ignored.
5. Deal with `incomes` and `expenses`.

We import the necessary packages here.

In [6]:
import numpy as np
import pandas as pd
import datetime
import ast

This is just for some basic text processing - it's used in (5).

In [2]:
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from string import punctuation as punctuation

## (1) Which filing codes can we ignore?

Let's look at a few codes. Recall that they are of the following form (omitting those starting with M and Y - midyear and annual reports - since there are none such in this time period).

In [1]:
filing_types=["RR","RA","Q1","Q1Y","1T","1TY","1A","1AY","1@","1@Y","Q2","Q2Y","2T","2TY","2A","2AY","2@","2@Y","Q3","Q3Y","3T","3TY","3A","3AY","3@","3@Y","Q4","Q4Y","4T","4TY","4A","4AY","4@","4@Y"]


|Code | Meaning| 
------|-------
|R | Registration |
|A |  Amendment |
|Q | Quarter |
|Y | No activity |
|T | Termination (lobbying for a client has finished) |
|@ | Termination amendment |

In the end, registrations and amendments to registrations (RR and RA) will not relevant to us, since there is no report of income or expenses on the registration form (this form is called form "LD-1" by the office of the Senate). See, for example, https://lda.senate.gov/filings/public/filing/286588cd-7cfd-4a82-a4a0-c5bd9265f868/print/.

It is worth noting that lobbying entities report `income` if they are lobbying on behalf of a client, and report `expenses` if they are lobbying on their own behalf (many companies employ in-house lobbyists).

For a quick sanity check, let's see if we ever have a report (in 2023 Q2) indicating both expenses and income.

In [3]:
df=pd.read_csv("../../lobbying-local-data/LDA_data/Filings_2023/filings_2023_Q2.csv")

In [306]:
df["expenses"]=df["expenses"].fillna(0)
df["income"]=df["income"].fillna(0)
df.loc[(df.income!=0) & (df.expenses!=0)]

Empty DataFrame
Columns: [url, filing_uuid, filing_type, filing_type_display, filing_year, filing_period, filing_period_display, filing_document_url, filing_document_content_type, income, expenses, expenses_method, expenses_method_display, posted_by_name, dt_posted, termination_date, registrant_country, registrant_ppb_country, registrant_address_1, registrant_address_2, registrant_different_address, registrant_city, registrant_state, registrant_zip, registrant, client, lobbying_activities, conviction_disclosures, foreign_entities, affiliated_organizations]
Index: []

[0 rows x 30 columns]

Good- this means we are safe to fill in missing values in these columns with zeros when the other has a non-zero value - basically, you are either reporting income or expenses.

 When both columns are zero, we should not just set the value to be zero- remember that income under $5000 is rounded down and reported to be zero (and similarly for expenses) and we should probably consider which column is relevant.

In [6]:
df["expenses"]=df["expenses"].fillna(0)
df.loc[df.expenses!=0]

url  \
4      https://lda.senate.gov/api/v1/filings/e4e51f25...   
8      https://lda.senate.gov/api/v1/filings/2126cffe...   
9      https://lda.senate.gov/api/v1/filings/a8669762...   
10     https://lda.senate.gov/api/v1/filings/07504ff3...   
12     https://lda.senate.gov/api/v1/filings/b8cd1bc0...   
...                                                  ...   
18331  https://lda.senate.gov/api/v1/filings/4e60ba4b...   
18337  https://lda.senate.gov/api/v1/filings/6c52acc6...   
18346  https://lda.senate.gov/api/v1/filings/59b3e8d8...   
18351  https://lda.senate.gov/api/v1/filings/f629416e...   
18360  https://lda.senate.gov/api/v1/filings/e8226e0e...   

                                filing_uuid filing_type  filing_year  income  \
4      e4e51f25-3310-4626-9fb1-1b0adbc11460          Q2         2023     NaN   
8      2126cffe-6bba-40e7-9a1d-6d25ec1aa0ee          Q2         2023     NaN   
9      a8669762-aa16-4ea5-9b7f-929e803d4e04          Q2         2023     NaN   
10     07504ff3-5feb-4003-a8a6-6ffd33e0cc1a          Q2         2023     NaN   
12     b8cd1bc0-6e62-45e0-a693-8fcae22ff5e8          Q2         2023     NaN   
...                                     ...         ...          ...     ...   
18331  4e60ba4b-a6c1-46e0-8fcc-cb3866058dae          Q2         2023     NaN   
18337  6c52acc6-7879-495a-bb36-fad8f62caa01          Q2         2023     NaN   
18346  59b3e8d8-81ee-4639-8fa0-330ca5188ee0          Q2         2023     NaN   
18351  f629416e-cd3b-4bb0-95f0-1539e7940bdc          Q2         2023     NaN   
18360  e8226e0e-1ed4-44c7-9c25-cb605d40d6db          Q2         2023     NaN   

       expenses expenses_method termination_date  \
4       10000.0               A              NaN   
8      160000.0               A              NaN   
9       80000.0               A              NaN   
10       8950.0               A              NaN   
12       5500.0               C              NaN   
...         ...             ...              ...   
18331  200000.0               A              NaN   
18337   53000.0               A              NaN   
18346   30000.0               A              NaN   
18351  987181.0               C              NaN   
18360   10000.0               A              NaN   

                                     lobbying_activities  \
4      [{'general_issue_code': 'MAR', 'general_issue_...   
8      [{'general_issue_code': 'GOV', 'general_issue_...   
9      [{'general_issue_code': 'HCR', 'general_issue_...   
10     [{'general_issue_code': 'DEF', 'general_issue_...   
12     [{'general_issue_code': 'MED', 'general_issue_...   
...                                                  ...   
18331  [{'general_issue_code': 'BUD', 'general_issue_...   
18337  [{'general_issue_code': 'HCR', 'general_issue_...   
18346  [{'general_issue_code': 'ROD', 'general_issue_...   
18351  [{'general_issue_code': 'ENV', 'general_issue_...   
18360  [{'general_issue_code': 'ECN', 'general_issue_...   

      conviction_disclosures foreign_entities affiliated_organizations  \
4                         []               []                       []   
8                         []               []                       []   
9                         []               []                       []   
10                        []               []                       []   
12                        []               []                       []   
...                      ...              ...                      ...   
18331                     []               []                       []   
18337                     []               []                       []   
18346                     []               []                       []   
18351                     []               []                       []   
18360                     []               []                       []   

                                                 reg     reg_id  \
4                OFFSHORE MARINE SERVICE ASSOCIATION     320771   
8 

In [39]:
df.loc[(df.income==0) & (df.expenses==0)]

url  \
5      https://lda.senate.gov/api/v1/filings/d38e586c...   
7      https://lda.senate.gov/api/v1/filings/fa3ad1c5...   
22     https://lda.senate.gov/api/v1/filings/d76c9559...   
23     https://lda.senate.gov/api/v1/filings/e8d79e69...   
24     https://lda.senate.gov/api/v1/filings/0c0c654a...   
...                                                  ...   
18341  https://lda.senate.gov/api/v1/filings/03e2502d...   
18343  https://lda.senate.gov/api/v1/filings/002e6ff1...   
18344  https://lda.senate.gov/api/v1/filings/306c5126...   
18349  https://lda.senate.gov/api/v1/filings/1b18d803...   
18350  https://lda.senate.gov/api/v1/filings/6403092e...   

                                filing_uuid filing_type   filing_type_display  \
5      d38e586c-0e64-4358-9be7-cb412e5f5343          Q2  2nd Quarter - Report   
7      fa3ad1c5-54bd-4b15-84f6-0ff4cef83f30          Q2  2nd Quarter - Report   
22     d76c9559-80b4-467e-b9f1-92927c8e370f          Q2  2nd Quarter - Report   
23     e8d79e69-6fa5-4c9c-bb81-933a3eec60c7          Q2  2nd Quarter - Report   
24     0c0c654a-67ac-4ca1-8bfd-dda626aa7868          Q2  2nd Quarter - Report   
...                                     ...         ...                   ...   
18341  03e2502d-c1fd-47bb-887c-481807daea3b          Q2  2nd Quarter - Report   
18343  002e6ff1-1657-4e06-a89c-b3cd8722fa5a          Q2  2nd Quarter - Report   
18344  306c5126-3096-4297-a104-ad92fcac343d          Q2  2nd Quarter - Report   
18349  1b18d803-5b7b-47be-a0d4-8c7d78fa1174          Q2  2nd Quarter - Report   
18350  6403092e-f6e1-40fc-b4a6-cde6b0ec2af2          Q2  2nd Quarter - Report   

       filing_year   filing_period          filing_period_display  \
5             2023  second_quarter  2nd Quarter (Apr 1 - June 30)   
7             2023  second_quarter  2nd Quarter (Apr 1 - June 30)   
22            2023  second_quarter  2nd Quarter (Apr 1 - June 30)   
23            2023  second_quarter  2nd Quarter (Apr 1 - June 30)   
24            2023  second_quarter  2nd Quarter (Apr 1 - June 30)   
...            ...             ...                            ...   
18341         2023  second_quarter  2nd Quarter (Apr 1 - June 30)   
18343         2023  second_quarter  2nd Quarter (Apr 1 - June 30)   
18344         2023  second_quarter  2nd Quarter (Apr 1 - June 30)   
18349         2023  second_quarter  2nd Quarter (Apr 1 - June 30)   
18350         2023  second_quarter  2nd Quarter (Apr 1 - June 30)   

                                     filing_document_url  \
5      https://lda.senate.gov/filings/public/filing/d...   
7      https://lda.senate.gov/filings/public/filing/f...   
22     https://lda.senate.gov/filings/public/filing/d...   
23     https://lda.senate.gov/filings/public/filing/e...   
24     https://lda.senate.gov/filings/public/filing/0...   
...                                                  ...   
18341  https://lda.senate.gov/filings/public/filing/0...   
18343  https://lda.senate.gov/filings/public/filing/0...   
18344  https://lda.senate.gov/filings/public/filing/3...   
18349  https://lda.senate.gov/filings/public/filing/1...   
18350  https://lda.senate.gov/filings/public/filing/6...   

      filing_document_content_type  income  ...  registrant_different_address  \
5                        text/html     0.0  ...                         False   
7                        text/html     0.0  ...                         False   
22                       text/html     0.0  ...                         False   
23                       text/html     0.0  ...                         False   
24                       text/html     0.0  ...                         False   
...                            ...     ...  ...                           ...   
18341                    text/html     0.0  ...                         False   
18343                    text/html     0.0  ...                         False   
18344                    text/html     0.0  ...                         False   

In [308]:
df["dt_posted"]

0        2023-04-17T13:52:00-04:00
1        2023-05-01T13:58:12-04:00
2        2023-05-04T11:20:38-04:00
3        2023-05-09T11:09:15-04:00
4        2023-05-12T17:03:04-04:00
                   ...            
18357    2024-02-29T13:42:10-05:00
18358    2024-02-29T17:25:48-05:00
18359    2024-02-29T23:56:20-05:00
18360    2024-03-03T20:40:18-05:00
18361    2024-03-04T16:35:38-05:00
Name: dt_posted, Length: 18362, dtype: object

Note all of these dataframes are ordered by `dt_posted`. This will be important to us later when dealing with duplicates.

Let's talk about filings involving the "no-activity" code Y. While it is tempting to toss such filings, it seems very possible that firms can report income or expenses when filing a Y code. This is definitely somewhat disturbing, but maybe this corresponds to being paid to do nothing (or paid just to keep a firm on retainer)?

In [57]:
lobbying_2023_Q1Y=pd.read_csv("../../lobbying-local-data/LDA_data/Filings_2023/filings_2023_Q1Y.csv")

In [61]:
lobbying_2023_Q1Y["expenses"]=lobbying_2023_Q1Y["expenses"].fillna(0)
lobbying_2023_Q1Y["income"]=lobbying_2023_Q1Y["income"].fillna(0)

In [63]:
lobbying_2023_Q1Y.loc[(lobbying_2023_Q1Y["expenses"]!=0) | (lobbying_2023_Q1Y["income"]!=0)]

url  \
4     https://lda.senate.gov/api/v1/filings/2f3f7ad4...   
27    https://lda.senate.gov/api/v1/filings/d18f7814...   
28    https://lda.senate.gov/api/v1/filings/0afef369...   
32    https://lda.senate.gov/api/v1/filings/22cb9607...   
38    https://lda.senate.gov/api/v1/filings/3e0840b3...   
...                                                 ...   
2416  https://lda.senate.gov/api/v1/filings/a8d42fc9...   
2417  https://lda.senate.gov/api/v1/filings/b10e92f1...   
2427  https://lda.senate.gov/api/v1/filings/9678095e...   
2433  https://lda.senate.gov/api/v1/filings/9e0a0976...   
2435  https://lda.senate.gov/api/v1/filings/7d57a313...   

                               filing_uuid filing_type  \
4     2f3f7ad4-aa65-4272-9748-cd6b2d486375         Q1Y   
27    d18f7814-89bb-43d2-b069-2ec862e55fed         Q1Y   
28    0afef369-ebe1-442e-9f82-2b123da38939         Q1Y   
32    22cb9607-85d5-48a0-a834-a593e69441f8         Q1Y   
38    3e0840b3-b361-43fb-8a18-31494f879e76         Q1Y   
...                                    ...         ...   
2416  a8d42fc9-621b-4cf0-81fa-d2248f727d8f         Q1Y   
2417  b10e92f1-f075-455c-aceb-f826d020b561         Q1Y   
2427  9678095e-ad4b-4c7e-a068-500641560c29         Q1Y   
2433  9e0a0976-a2f1-4f66-9206-499d593a1c96         Q1Y   
2435  7d57a313-0b80-44bb-837f-7a84b979a088         Q1Y   

                     filing_type_display  filing_year  filing_period  \
4     1st Quarter - Report (No Activity)         2023  first_quarter   
27    1st Quarter - Report (No Activity)         2023  first_quarter   
28    1st Quarter - Report (No Activity)         2023  first_quarter   
32    1st Quarter - Report (No Activity)         2023  first_quarter   
38    1st Quarter - Report (No Activity)         2023  first_quarter   
...                                  ...          ...            ...   
2416  1st Quarter - Report (No Activity)         2023  first_quarter   
2417  1st Quarter - Report (No Activity)         2023  first_quarter   
2427  1st Quarter - Report (No Activity)         2023  first_quarter   
2433  1st Quarter - Report (No Activity)         2023  first_quarter   
2435  1st Quarter - Report (No Activity)         2023  first_quarter   

             filing_period_display  \
4     1st Quarter (Jan 1 - Mar 31)   
27    1st Quarter (Jan 1 - Mar 31)   
28    1st Quarter (Jan 1 - Mar 31)   
32    1st Quarter (Jan 1 - Mar 31)   
38    1st Quarter (Jan 1 - Mar 31)   
...                            ...   
2416  1st Quarter (Jan 1 - Mar 31)   
2417  1st Quarter (Jan 1 - Mar 31)   
2427  1st Quarter (Jan 1 - Mar 31)   
2433  1st Quarter (Jan 1 - Mar 31)   
2435  1st Quarter (Jan 1 - Mar 31)   

                                    filing_document_url  \
4     https://lda.senate.gov/filings/public/filing/2...   
27    https://lda.senate.gov/filings/public/filing/d...   
28    https://lda.senate.gov/filings/public/filing/0...   
32    https://lda.senate.gov/filings/public/filing/2...   
38    https://lda.senate.gov/filings/public/filing/3...   
...                                                 ...   
2416  https://lda.senate.gov/filings/public/filing/a...   
2417  https://lda.senate.gov/filings/public/filing/b...   
2427  https://lda.senate.gov/filings/public/filing/9...   
2433  https://lda.senate.gov/filings/public/filing/9...   
2435  https://lda.senate.gov/filings/public/filing/7...   

     filing_document_content_type   income  ...  registrant_different_address  \
4                       text/html  10000.0  ...                         False   
27                      text/html      0.0  ...                          True   
28                      text/html  15000.0  ...                         False   
32                      text/html  30000.0  ...                         False   
38                      text/html  30000.0  ...                          True   
...                           ...      ...  ...                           ...   
2416                    text/html  12000.0  ... 

So yeah, that can happen. This definitely is not what I though "no activity" would mean...

 Keep in mind too that having missing entries in both income and expenses doesn't necessarily imply that there was no lobbying that quarter - those columns have entries representing a range, so it really means something like less than $m$, where $m$ is the minimum reporting value.

OK, this has been a little all over the place. But here's our first conclusion: we will definitely omit the R (registration) codes. That leaves:

In [6]:
relevant_filing_types=["Q1","Q1Y","1T","1TY","1A","1AY","1@","1@Y","Q2","Q2Y","2T","2TY","2A","2AY","2@","2@Y","Q3","Q3Y","3T","3TY","3A","3AY","3@","3@Y","Q4","Q4Y","4T","4TY","4A","4AY","4@","4@Y"]

I am also going to standardize these codes so that the unnecessary prefix Q is removed. That leaves us with the codes below.

In [7]:
stand_filing_types=["1","1Y","1T","1TY","1A","1AY","1@","1@Y","2","2Y","2T","2TY","2A","2AY","2@","2@Y","3","3Y","3T","3TY","3A","3AY","3@","3@Y","4","4Y","4T","4TY","4A","4AY","4@","4@Y"]

The dictionary relating them is:

In [8]:
rel_2_stand=dict(zip(relevant_filing_types, stand_filing_types))

In [35]:
stand_2_rel=dict(zip(stand_filing_types, relevant_filing_types))

When I export files again, it will be with these standardized ones.

## (2) Column hygiene

Let's look at those 2023 Q2 filings again.

In [129]:
df=pd.read_csv("../../lobbying-local-data/LDA_data/Filings_2023/filings_2023_Q2.csv")


Just to see what the columns are, and what a typical entry may look like, here's the 57th row of one of these dataframes, printed out vertically.

In [5]:
df.iloc[57]

url                             https://lda.senate.gov/api/v1/filings/e7af16b4...
filing_uuid                                  e7af16b4-d06b-4230-bc30-05d781846aea
filing_type                                                                    Q2
filing_type_display                                          2nd Quarter - Report
filing_year                                                                  2023
filing_period                                                      second_quarter
filing_period_display                               2nd Quarter (Apr 1 - June 30)
filing_document_url             https://lda.senate.gov/filings/public/filing/e...
filing_document_content_type                                            text/html
income                                                                    60000.0
expenses                                                                      NaN
expenses_method                                                               NaN
expenses_method_

A lot of these columns seem to be unimportant. At a first glance, I don't think we will ever use: `["url","filing_type_display", "filing_period", "filing_period_display", "filing_document_url", "filing_document_content_type", "expenses_method_display","posted_by_name","termination_date, "registrant_country", "registrant_ppb_country", "registrant_address_1", "registrant_address_2", "registrant_different_address", "registrant_city", "registrant_state", "registrant_zip"]`. Keeping the uuid is useful if we need to refer to this specific filing for any reason. 

`expenses_method` (and the redundant `expenses_method_display`) seems to be about whether the registrant wants to report their expenses according to various IRC definitions of lobbying, or the LDA definition. See https://lda.congress.gov/ld/help/default.htm?turl=Documents%2FAppLD2.htm under "Reporting methods." I think we can ignore it, but I keep it for now.

In [87]:
dropped_columns=["url","filing_type_display", "filing_period", "filing_period_display", "filing_document_url", "filing_document_content_type", "expenses_method", "expenses_method_display","posted_by_name", "termination_date" , "registrant_country", "registrant_ppb_country", "registrant_address_1", "registrant_address_2", "registrant_different_address", "registrant_city", "registrant_state", "registrant_zip"]
lobbying_2023_Q2=df.drop(labels=dropped_columns, axis=1)
lobbying_2023_Q2.iloc[57]

filing_uuid                              e7af16b4-d06b-4230-bc30-05d781846aea
filing_type                                                                Q2
filing_year                                                              2023
income                                                                60000.0
expenses                                                                  NaN
dt_posted                                           2023-06-29T13:33:07-04:00
registrant                  {'id': 401103287, 'url': 'https://lda.senate.g...
client                      {'id': 198399, 'url': 'https://lda.senate.gov/...
lobbying_activities         [{'general_issue_code': 'PHA', 'general_issue_...
conviction_disclosures                                                     []
foreign_entities                                                           []
affiliated_organizations                                                   []
Name: 57, dtype: object

This looks a lot less overwhelming to me!

Now, what's going on with the `registrant`, `client`, `lobbying_activities`, `conviction_disclosures`, `foreign_entities`, and `affiliated_organizations` columns?

#### Dealing with dictionaries in the DataFrames

There are list and dictionary literals in the `registrant`, `client`, `lobbying_activities`, `conviction_disclosures`, `foreign_entities`, and `affiliated_organizations` columns columns. We would like to extract out the contents of these to make the data easier to look at.

In [78]:
ast.literal_eval(df.iloc[57].registrant)

{'id': 401103287,
 'url': 'https://lda.senate.gov/api/v1/registrants/401103287/',
 'house_registrant_id': 401103287,
 'name': 'MCDERMOTT+CONSULTING LLC',
 'description': 'Consulting Firm',
 'address_1': '500 North Capitol Street, NW',
 'address_2': None,
 'address_3': None,
 'address_4': None,
 'city': 'Washington',
 'state': 'DC',
 'state_display': 'District of Columbia',
 'zip': '20001',
 'country': 'US',
 'country_display': 'United States of America',
 'ppb_country': 'US',
 'ppb_country_display': 'United States of America',
 'contact_name': 'ERIC ZIMMERMAN',
 'contact_telephone': '+1 202-204-1457',
 'dt_updated': '2024-01-02T12:57:52.578475-05:00'}

From this, we only really want the name and id number. What about `client`?

In [28]:
ast.literal_eval(df.iloc[57].client)

{'id': 198399,
 'url': 'https://lda.senate.gov/api/v1/clients/198399/',
 'client_id': 24,
 'name': 'ALLIANCE FOR RURAL HOSPITAL ACCESS',
 'general_description': 'Coalition of Rural Referral Centers and Sole Community Hospitals',
 'client_government_entity': False,
 'client_self_select': None,
 'state': 'DC',
 'state_display': 'District of Columbia',
 'country': 'US',
 'country_display': 'United States of America',
 'ppb_state': 'DC',
 'ppb_state_display': 'District of Columbia',
 'ppb_country': 'US',
 'ppb_country_display': 'United States of America',
 'effective_date': '2014-04-01'}

Same here: we only want the name and id number.

The `lobbying_activities` column contains a string literal representing a list of dictionaries. We can see that these dictionaries contain a lot of information on the lobbying activity: names of lobbyists, descriptions of the lobbying, and most importantly, the codes describing the lobbying sector.

In [29]:
ast.literal_eval(df.iloc[57].lobbying_activities)

[{'general_issue_code': 'PHA',
  'general_issue_code_display': 'Pharmacy',
  'description': 'Amendments to Section 340B of the Public Health Service Act regarding eligibility for rural referral centers and sole community hospitals in the federal discount drug purchasing program.',
  'foreign_entity_issues': '',
  'lobbyists': [{'lobbyist': {'id': 60423,
     'prefix': None,
     'prefix_display': None,
     'first_name': 'ERIC',
     'nickname': None,
     'middle_name': None,
     'last_name': 'ZIMMERMAN',
     'suffix': None,
     'suffix_display': None},
    'covered_position': None,
    'new': False},
   {'lobbyist': {'id': 60428,
     'prefix': None,
     'prefix_display': None,
     'first_name': 'ERICA',
     'nickname': None,
     'middle_name': None,
     'last_name': 'STOCKER',
     'suffix': None,
     'suffix_display': None},
    'covered_position': '2000-2009: Staff Assistant, Legislative Correspondent, Legislative Assistant, Deputy Chief of Staff, Rep. Jim Saxton',
    'n

Let's extract those codes.

In [37]:
k=len(ast.literal_eval(df.iloc[57].lobbying_activities))
issue_codes= [ast.literal_eval(df.iloc[57].lobbying_activities)[i]['general_issue_code'] for i in range(k)]
issue_codes

['PHA', 'MMM']

Let's also grab the government entities lobbied. I'll drop duplicates by making it a set.

In [134]:
k=len(ast.literal_eval(df.iloc[57].lobbying_activities))
entities= [ast.literal_eval(df.iloc[57].lobbying_activities)[i]['government_entities'] for i in range(k)]
ents=[]
for j in range(len(entities)):
    for k in range(len(entities[j])):
        ents.append(entities[j][k]['name'])
ents=set(ents)

Finally, we take a description of the lobbying activities.

In [100]:
k=len(ast.literal_eval(df.iloc[57].lobbying_activities))
description = [ast.literal_eval(df.iloc[57].lobbying_activities)[i]['description'] for i in range(k)]

Now, we should investigate the often empty `conviction_disclosures`, `foreign_entities`, and `affiliated_organizations`  columns. Entries still look to be lists of dictionaries, like for `lobbying_activities`.

In [17]:
ast.literal_eval(df.loc[df.conviction_disclosures!='[]'].iloc[0]['conviction_disclosures'])

[{'lobbyist': {'id': 29268,
   'prefix': None,
   'prefix_display': None,
   'first_name': 'C',
   'nickname': None,
   'middle_name': 'JAMES',
   'last_name': 'PATTI',
   'suffix': None,
   'suffix_display': None},
  'date': '2002-05-07',
  'description': 'Violation of one count of 18 USC 1341; sentenced to two years of probation'}]

From this, I don't think there is anything I really want - maybe a `True` or `False` depending on whether or not there are any such disclosures. It's extremely unlikely we'll go into tracking individual lobbyists, even if they have convictions.

As for foreign entities, we can record the name and country.

In [79]:
for_ent=ast.literal_eval(df.loc[df.foreign_entities!='[]'].iloc[0]['foreign_entities'])
for_ent

[{'name': 'SK HOLDINGS',
  'contribution': '0.00',
  'ownership_percentage': '100.00',
  'address': '26, Jong-ro, Jongno-gu',
  'city': 'Seoul',
  'state': None,
  'state_display': None,
  'country': 'KR',
  'country_display': 'South Korea',
  'ppb_city': 'Seoul',
  'ppb_state': None,
  'ppb_state_display': None,
  'ppb_country': 'KR',
  'ppb_country_display': 'South Korea'}]

In [90]:
k=len(for_ent)
foreign_entities=[(for_ent[i]['name'],for_ent[i]['country_display']) for i in range(k)]
foreign_entities

[('SK HOLDINGS', 'South Korea')]

In [76]:
aff_org=ast.literal_eval(df.loc[df.affiliated_organizations!='[]'].iloc[0]['affiliated_organizations'])
aff_org

[{'name': 'CAPITOL INTEGRATION',
  'url': None,
  'address_1': '7904 Heritage Grand Place',
  'address_2': None,
  'address_3': None,
  'address_4': None,
  'city': 'Bradenton',
  'state': 'FL',
  'state_display': 'Florida',
  'zip': '34212',
  'country': 'US',
  'country_display': 'United States of America',
  'ppb_city': None,
  'ppb_state': 'FL',
  'ppb_state_display': 'Florida',
  'ppb_country': 'US',
  'ppb_country_display': 'United States of America'}]

In [92]:
k=len(aff_org)
aff_orgs=[aff_org[i]['name'] for i in range(k)]
aff_orgs

['CAPITOL INTEGRATION']

OK, we're ready to clean up some columns. First, a trial run on 2022_Q2.

In [112]:
dropped_columns=["url","filing_type_display", "filing_period", "filing_period_display", "filing_document_url", "filing_document_content_type", "expenses_method_display","posted_by_name", "termination_date","registrant_country", "registrant_ppb_country", "registrant_address_1", "registrant_address_2", "registrant_different_address", "registrant_city", "registrant_state", "registrant_zip"]
df=pd.read_csv("../../lobbying-local-data/LDA_data/Filings_2023/filings_2023_Q2.csv")
reg=[] #these lists will store data for our new columns
affiliated_orgs=[]
cl=[]
foreign_entities=[]
issue_codes=[]
entities_lobbied=[]
lobbying_description=[]
reg_ids=[]
cl_ids=[]
for j in range(len(df)):
    reg.append(ast.literal_eval(df.iloc[j]["registrant"])["name"])
    aff_org=ast.literal_eval(df.iloc[j]['affiliated_organizations']) #grabbing affiliated orgs
    k=len(aff_org)
    aff_orgs_j=[aff_org[i]['name'] for i in range(k)]
    affiliated_orgs.append(aff_orgs_j)
    cl.append(ast.literal_eval(df.iloc[j]["client"])["name"])
    for_ent=ast.literal_eval(df.iloc[j]['foreign_entities']) #grabbing foreign entities
    k=len(for_ent)
    for_ent_j=[(for_ent[i]['name'],for_ent[i]['country_display']) for i in range(k)]
    foreign_entities.append(for_ent_j)
    lobb_act=ast.literal_eval(df.iloc[j]['lobbying_activities']) #extracting out lobbying issue codes from the lobbying_activities column
    k=len(lobb_act) 
    issue_codes_j= [lobb_act[i]['general_issue_code'] for i in range(k)]
    issue_codes.append(issue_codes_j)
    entities=[lobb_act[i]['government_entities'] for i in range(k)] #entities lobbied
    ents=[]
    for l in range(len(entities)):
        for m in range(len(entities[l])):
            ents.append(entities[l][m]['name'])
    ents=list(set(ents))
    ents.sort()
    entities_lobbied.append(ents)
    description_j=[lobb_act[i]['description'] for i in range(k)]
    lobbying_description.append(description_j)
    reg_ids.append(ast.literal_eval(df.iloc[j]["registrant"])["id"])
    cl_ids.append(ast.literal_eval(df.iloc[j]["client"])["id"])

df["registrant"]=reg      #making new columns
df["affiliated_organizations"]=affiliated_orgs
df["client"]=cl
df["foreign_entities"]=foreign_entities
df["issue_codes"]=issue_codes
df["entities_lobbied"]=entities_lobbied
df["lobbying_description"]=lobbying_description
df["reg_id"]=reg_ids
df["cl_id"]=cl_ids
df["JACK_conviction"]=False #JACK_conviction just keeps track of if there is a non-empty entry in conviction_disclosures
df.loc[df.conviction_disclosures!='[]', 'JACK_conviction']=True

df=df.drop(labels=dropped_columns, axis=1) #get rid of the useless columns
df=df.drop(labels=['lobbying_activities','conviction_disclosures'], axis=1) #also drop lobbying_activities and conviction_disclosures as we have gotten what we need from them
df=df.fillna(0) #fills all missing values with 0 - NaNs were only in income, expenses, and expenses_method

Let me write a small function that computes, given a dataframe of filings `df` and a row `i`, the range of dates the appropriate quarter covers. I'll encode this range as a dictionary storing a start and end date.

In [45]:
def filing_period(df,i):
    yr=df.iloc[i]['filing_year']
    quarter=rel_2_stand[df.iloc[i]['filing_type']][0]
    if quarter=='1':
        d= {'start' : datetime.date(year=yr, month=1, day=1), 'end' : datetime.date(year=yr, month=3, day=31)}
    if quarter=='2':
        d= {'start' : datetime.date(year=yr, month=4, day=1), 'end' : datetime.date(year=yr, month=6, day=30)}
    if quarter=='3':
        d= {'start' : datetime.date(year=yr, month=7, day=1), 'end' : datetime.date(year=yr, month=9, day=30)}
    if quarter=='4':
        d= {'start' : datetime.date(year=yr, month=10, day=1), 'end' : datetime.date(year=yr, month=12, day=31)}
    return d

For our purposes this is overkill - all of our dataframes up to now have the same year and quarter. Still, let's use this to replace the filing year column with a column that tracks the filing period in this format.

In [103]:
df['filing_period']=[filing_period(df,i) for i in range(len(df))] #could do 0 instead of i since all filings in this dataframe have the same period

In [104]:
df=df.drop(labels=['filing_year'], axis=1)

We now reorder the columns so that they are easier to read at a glance.

In [105]:
cols=list(df.columns.values)
print(list(enumerate(cols)))

[(0, 'filing_uuid'), (1, 'filing_type'), (2, 'income'), (3, 'expenses'), (4, 'expenses_method'), (5, 'dt_posted'), (6, 'registrant'), (7, 'client'), (8, 'foreign_entities'), (9, 'affiliated_organizations'), (10, 'issue_codes'), (11, 'entities_lobbied'), (12, 'lobbying_description'), (13, 'reg_id'), (14, 'cl_id'), (15, 'JACK_conviction'), (16, 'filing_period')]


In [106]:
cols=cols[6:8]+cols[2:4]+cols[10:13]+cols[8:10]+cols[15:16]+cols[0:2]+cols[4:6]+cols[13:15]

In [107]:
cols

['registrant',
 'client',
 'income',
 'expenses',
 'issue_codes',
 'entities_lobbied',
 'lobbying_description',
 'foreign_entities',
 'affiliated_organizations',
 'JACK_conviction',
 'filing_uuid',
 'filing_type',
 'expenses_method',
 'dt_posted',
 'reg_id',
 'cl_id']

In [108]:
df=df[cols]

OK, let's assemble this all into a function that cleans a dataframe.

In [7]:
def filing_period(df,i):
    yr=df.iloc[i]['filing_year']
    quarter=rel_2_stand[df.iloc[i]['filing_type']][0]
    if quarter=='1':
        d= {'start' : datetime.date(year=yr, month=1, day=1), 'end' : datetime.date(year=yr, month=3, day=31)}
    if quarter=='2':
        d= {'start' : datetime.date(year=yr, month=4, day=1), 'end' : datetime.date(year=yr, month=6, day=30)}
    if quarter=='3':
        d= {'start' : datetime.date(year=yr, month=7, day=1), 'end' : datetime.date(year=yr, month=9, day=30)}
    if quarter=='4':
        d= {'start' : datetime.date(year=yr, month=10, day=1), 'end' : datetime.date(year=yr, month=12, day=31)}
    return d

def clean_cols(df):
    dropped_columns=["url","filing_type_display", "filing_period", "filing_period_display", "filing_document_url", "filing_document_content_type", "expenses_method_display","posted_by_name", "termination_date","registrant_country", "registrant_ppb_country", "registrant_address_1", "registrant_address_2", "registrant_different_address", "registrant_city", "registrant_state", "registrant_zip"]
    reg=[] #these lists will store data for our new columns
    affiliated_orgs=[]
    cl=[]
    foreign_entities=[]
    issue_codes=[]
    entities_lobbied=[]
    lobbying_description=[]
    reg_ids=[]
    cl_ids=[]
    dts=[]
    for j in range(len(df)):
        reg.append(ast.literal_eval(df.iloc[j]["registrant"])["name"])
        aff_org=ast.literal_eval(df.iloc[j]['affiliated_organizations']) #grabbing affiliated orgs
        k=len(aff_org)
        aff_orgs_j=[aff_org[i]['name'] for i in range(k)]
        affiliated_orgs.append(aff_orgs_j)
        cl.append(ast.literal_eval(df.iloc[j]["client"])["name"])
        for_ent=ast.literal_eval(df.iloc[j]['foreign_entities']) #grabbing foreign entities
        k=len(for_ent)
        for_ent_j=[(for_ent[i]['name'],for_ent[i]['country_display']) for i in range(k)]
        foreign_entities.append(for_ent_j)
        lobb_act=ast.literal_eval(df.iloc[j]['lobbying_activities']) #extracting out lobbying issue codes from the lobbying_activities column
        k=len(lobb_act) 
        issue_codes_j= [lobb_act[i]['general_issue_code'] for i in range(k)]
        issue_codes.append(issue_codes_j)
        entities=[lobb_act[i]['government_entities'] for i in range(k)] #entities lobbied
        ents=[]
        for l in range(len(entities)):
            for m in range(len(entities[l])):
                ents.append(entities[l][m]['name'])
        ents=list(set(ents))
        ents.sort()
        entities_lobbied.append(ents)
        description_j=[lobb_act[i]['description'] for i in range(k)]
        lobbying_description.append(description_j)
        reg_ids.append(ast.literal_eval(df.iloc[j]["registrant"])["id"])
        cl_ids.append(ast.literal_eval(df.iloc[j]["client"])["id"])
        dts.append(df.iloc[j]["dt_posted"][:-6]) #cleaning the dt_posted column

    df["registrant"]=reg      #making new columns
    df["affiliated_organizations"]=affiliated_orgs
    df["client"]=cl
    df["foreign_entities"]=foreign_entities
    df["issue_codes"]=issue_codes
    df["entities_lobbied"]=entities_lobbied
    df["lobbying_description"]=lobbying_description
    df["reg_id"]=reg_ids
    df["cl_id"]=cl_ids
    df["JACK_conviction"]=False #JACK_conviction just keeps track of if there is a non-empty entry in conviction_disclosures
    df.loc[df.conviction_disclosures!='[]', 'JACK_conviction']=True
    df["dt_posted"]=dts
    df['dt_posted']=pd.to_datetime(df['dt_posted'], format='%Y-%m-%dT%H:%M:%S') #turning the dt_posted column into datetimes

    df=df.drop(labels=dropped_columns, axis=1) #get rid of the useless columns
    df=df.drop(labels=['lobbying_activities','conviction_disclosures'], axis=1) #also drop lobbying_activities and conviction_disclosures as we have gotten what we need from them
    df=df.fillna(0) #fills all missing values with 0 - NaNs were only in income, expenses, and expenses_method
    df['filing_period']=[filing_period(df,i) for i in range(len(df))] #could do 0 instead of i since all filings in this dataframe have the same period
    df=df.drop(labels=['filing_year'], axis=1)
    cols=list(df.columns.values)
    cols=cols[6:8]+cols[2:4]+cols[10:13]+cols[8:10]+cols[15:16]+cols[0:2]+cols[4:6]+cols[13:15]
    df=df[cols]
    return df
    

## (3) Row hygiene

There are duplicate entries in the filings. For instance, look at our dataframe again.

In [139]:
df=clean_cols(pd.read_csv("../../lobbying-local-data/LDA_data/Filings_2023/filings_2023_Q2.csv"))

In [138]:
type(df.iloc[2]['dt_posted'])

pandas._libs.tslibs.timestamps.Timestamp

In [127]:
type(df.loc[2]['dt_posted'])

pandas._libs.tslibs.timestamps.Timestamp

In [116]:
ids=set() #ids is a set to avoid double-counting
duplicated_ids=pd.DataFrame()
for i in range(len(df)):
    ids.add((df.iloc[i]['reg_id'],df.iloc[i]['cl_id']))  #we add data as a tuple, since sets of lists are not allowed in python
ids_list = list(ids) #turning ids into a list so we can iterate through the entries (sets are unordered)
for j in range(len(ids_list)):
    if len(df.loc[(df.reg_id==ids_list[j][0]) & (df.cl_id==ids_list[j][1]) ])>1:
        duplicated_ids=pd.concat([duplicated_ids, df.loc[(df.reg_id==ids_list[j][0]) & (df.cl_id==ids_list[j][1])]])
duplicated_ids

registrant  \
4028                           O'NEILL AND ASSOCIATES   
4031                           O'NEILL AND ASSOCIATES   
953   SHORELIGHT, LLC (FKA SHORELIGHT EDUCATION, LLC)   
1080  SHORELIGHT, LLC (FKA SHORELIGHT EDUCATION, LLC)   
1121                          LANTHEUS HOLDINGS, INC.   
...                                               ...   
26                                      KERRY O'BRIEN   
4165                     MCCARTHY STRATEGIC SOLUTIONS   
4169                     MCCARTHY STRATEGIC SOLUTIONS   
6997               PUBLIC STRATEGIES WASHINGTON, INC.   
6999               PUBLIC STRATEGIES WASHINGTON, INC.   

                                               client   income  expenses  \
4028                 EV TRANSPORTATION SERVICES, INC.  15000.0       0.0   
4031                 EV TRANSPORTATION SERVICES, INC.  15000.0       0.0   
953   SHORELIGHT, LLC (FKA SHORELIGHT EDUCATION, LLC)      0.0   48700.0   
1080  SHORELIGHT, LLC (FKA SHORELIGHT EDUCATION, LLC)      0.0   48700.0   
1121                          LANTHEUS HOLDINGS, INC.      0.0  110000.0   
...                                               ...      ...       ...   
26                 NATIONAL DOMESTIC WORKERS ALLIANCE  10000.0       0.0   
4165                                     INOTIV, INC.      0.0       0.0   
4169                                     INOTIV, INC.      0.0       0.0   
6997                                NOVO NORDISK INC.  30000.0       0.0   
6999                                NOVO NORDISK INC.  30000.0       0.0   

     issue_codes                                   entities_lobbied  \
4028       [POS]                 [HOUSE OF REPRESENTATIVES, SENATE]   
4031       [POS]  [HOUSE OF REPRESENTATIVES, SENATE, U.S. Postal...   
953   [EDU, IMM]  [Commerce, Dept of (DOC), HOUSE OF REPRESENTAT...   
1080  [EDU, IMM]  [Commerce, Dept of (DOC), HOUSE OF REPRESENTAT...   
1121       [MMM]                 [HOUSE OF REPRESENTATIVES, SENATE]   
...          ...                                                ...   
26         [LBR]  [HOUSE OF REPRESENTATIVES, Office of Science &...   
4165  [MED, ANI]                 [HOUSE OF REPRESENTATIVES, SENATE]   
4169  [MED, ANI]                 [HOUSE OF REPRESENTATIVES, SENATE]   
6997       [MMM]                 [HOUSE OF REPRESENTATIVES, SENATE]   
6999       [MMM]                 [HOUSE OF REPRESENTATIVES, SENATE]   

                                   lobbying_description foreign_entities  \
4028  [Electric vehicle/delivery transportation-rela...               []   
4031  [Electric vehicle/delivery transportation-rela...               []   
953   [Immigration pertaining to international stude...               []   
1080  [Immigration pertaining to international stude...               []   
1121  [Medicare HOPPS separate payment for high-prec...               []   
...                                                 ...              ...   
26    [Rights and responsibilities of domestic worke...               []   
4165  [Animal research models to biopharmaceuticals,...               []   
4169  [Animal research models to biopharmaceuticals,...               []   
6997  [Issues related to the coverage of obesity the...               []   
6999  [Issues related to the coverage of obesity the...               []   

     affiliated_organizations  JACK_conviction  \
4028                       []            False   
4031                       []            False   
953                        []            False   
1080                       []            False   
1121                       []            False   
...                       ...              ...   
26                         []            False   
4165                       []            False   
4169                       []            False   
6997                       []            False   
6999                       []            False   

                               filing_uuid filing_type expenses_method  \
4028

In [117]:
duped_ids=set()
for i in range(len(duplicated_ids)):
    duped_ids.add((duplicated_ids.iloc[i]['reg_id'],duplicated_ids.iloc[i]['cl_id']))
duped_list = list(duped_ids)
len(duped_list)

45

Here, 45 filings were actually filed twice. These are probably just due to some human error. But, in theory, there may be slight variations between these filings - we can stare at `duplicated_ids` to see this.

OK, moving forward we will just use the `drop_duplicates` function to remove dupes. We will keep the last, since the dataframes are all ordered by `dt_posted` naturally.

## (4) Updating quarterly filings according to amendments

Recall that some filings (with codes involving A or @) are amendments to previous filings. Let's take a look at one of these:

In [13]:
df_A = clean_cols(pd.read_csv("../../lobbying-local-data/LDA_data/Filings_2023/filings_2023_2A.csv"))
dropped_A=df_A.drop_duplicates(subset=['reg_id','cl_id'], keep='last')
print(df_A.info())
print()
print(dropped_A.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 608 entries, 0 to 607
Data columns (total 16 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   registrant                608 non-null    object 
 1   client                    608 non-null    object 
 2   income                    608 non-null    float64
 3   expenses                  608 non-null    float64
 4   issue_codes               608 non-null    object 
 5   entities_lobbied          608 non-null    object 
 6   lobbying_description      608 non-null    object 
 7   foreign_entities          608 non-null    object 
 8   affiliated_organizations  608 non-null    object 
 9   JACK_conviction           608 non-null    bool   
 10  filing_uuid               608 non-null    object 
 11  filing_type               608 non-null    object 
 12  expenses_method           608 non-null    object 
 13  dt_posted                 608 non-null    object 
 14  reg_id    

There are 608 amendments filed in Q2 of 2023, of these, there are 541 non-duplicates.

In [46]:
df=clean_cols(pd.read_csv("../../lobbying-local-data/LDA_data/Filings_2023/filings_2023_Q2.csv"))
dropped=df.drop_duplicates(subset=['reg_id','cl_id'], keep='last')
print(df.info())
print()
print(dropped.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18362 entries, 0 to 18361
Data columns (total 16 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   registrant                18362 non-null  object 
 1   client                    18362 non-null  object 
 2   income                    18362 non-null  float64
 3   expenses                  18362 non-null  float64
 4   issue_codes               18362 non-null  object 
 5   entities_lobbied          18362 non-null  object 
 6   lobbying_description      18362 non-null  object 
 7   foreign_entities          18362 non-null  object 
 8   affiliated_organizations  18362 non-null  object 
 9   JACK_conviction           18362 non-null  bool   
 10  filing_uuid               18362 non-null  object 
 11  filing_type               18362 non-null  object 
 12  expenses_method           18362 non-null  object 
 13  dt_posted                 18362 non-null  object 
 14  reg_id

There are 18362 Q2 filings for 2023, of which 18317 are non-duplicates. How many of these correspond to entries in "lobbying_2023_2A"? We can check.

In [15]:
df_toamend=pd.DataFrame()
df_fromamend=pd.DataFrame()
for i in range(len(dropped_A)):
    reg_id_to_find=dropped_A.iloc[i]['reg_id']
    cl_id_to_find=dropped_A.iloc[i]['cl_id']
    dropped_A_i=pd.DataFrame(dropped_A.iloc[[i]])
    dropped_i=pd.DataFrame(dropped.loc[(dropped.reg_id==reg_id_to_find) &  (dropped.cl_id==cl_id_to_find)])
    df_toamend=pd.concat([df_toamend,dropped_i])
    if len(dropped_i)>0:
        df_fromamend=pd.concat([df_fromamend, dropped_A_i])

Here we make two dataframes: the first, "df_toamend", lists all the original filings in Q2 2023 that match the registrant and client ids for an amendment filed in Q2 2023; the second, "df_fromamend," keeps track of all of the amendments matching those original filings.

Just a sanity check: these two should have the same number of filings in them.

In [16]:
print(len(df_toamend))
print()
print(len(df_fromamend))

432

432


Let's just take a peek at some of the amendments and the filings they are modifying, just to make sure everything is lining up correctly.

In [17]:
k=np.random.randint(0,423)
df_toamend.iloc[range(k,k+10)]

registrant  \
13009                              ARENA STRATEGIES, LLC   
2951   EMERGENCY DEPARTMENT PRACTICE MANAGEMENT ASSOC...   
6166                                 HARDWOOD FEDERATION   
15976                                FILECOIN FOUNDATION   
1266                           MG HOUSING STRATEGIES LLC   
1267                           MG HOUSING STRATEGIES LLC   
1268                           MG HOUSING STRATEGIES LLC   
1269                           MG HOUSING STRATEGIES LLC   
1270                           MG HOUSING STRATEGIES LLC   
1271                           MG HOUSING STRATEGIES LLC   

                                                  client   income  expenses  \
13009                            INDEPENDENCE BLUE CROSS  18750.0       0.0   
2951   EMERGENCY DEPARTMENT PRACTICE MANAGEMENT ASSOC...      0.0    6000.0   
6166                                 HARDWOOD FEDERATION      0.0  148000.0   
15976                                FILECOIN FOUNDATION      0.0   70000.0   
1266                                                CREA  20000.0       0.0   
1267                                        INLAND GROUP  10000.0       0.0   
1268                               THE PACIFIC COMPANIES   7500.0       0.0   
1269                           WENDOVER HOUSING PARTNERS  10000.0       0.0   
1270                                       THE NRP GROUP  10000.0       0.0   
1271                                 CHURCHILL STATESIDE   5000.0       0.0   

                     issue_codes  \
13009            [MMM, INS, HCR]   
2951                       [HCR]   
6166        [AGR, TRD, TRU, TAX]   
15976  [SCI, FIN, CPI, CDT, BAN]   
1266                       [HOU]   
1267                       [HOU]   
1268                       [HOU]   
1269                       [HOU]   
1270                       [HOU]   
1271                       [HOU]   

                                        entities_lobbied  \
13009                 [HOUSE OF REPRESENTATIVES, SENATE]   
2951   [Centers For Medicare and Medicaid Services (C...   
6166   [Agriculture, Dept of (USDA), Federal Maritime...   
15976                 [HOUSE OF REPRESENTATIVES, SENATE]   
1266   [HOUSE OF REPRESENTATIVES, SENATE, White House...   
1267                  [HOUSE OF REPRESENTATIVES, SENATE]   
1268                  [HOUSE OF REPRESENTATIVES, SENATE]   
1269                  [HOUSE OF REPRESENTATIVES, SENATE]   
1270                  [HOUSE OF REPRESENTATIVES, SENATE]   
1271                  [HOUSE OF REPRESENTATIVES, SENATE]   

                                    lobbying_description foreign_entities  \
13009        [Medicare/Medicaid, Insurance, Health Care]               []   
2951   [Implementation of the No Surprises Act Telehe...               []   
6166   [Farm Bill Reauthorization - wood products-rel...               []   
15976  [General Discussions related to digital assets...               []   
1266             [Low-Income Housing Tax Credit program]               []   
1267             [Low-Income Housing Tax Credit program]               []   
1268             [Low-Income Housing Tax Credit program]               []   
1269             [Low-Income Housing Tax Credit program]               []   
1270             [Low-Income Housing Tax Credit program]               []   
1271             [Low-Income Housing Tax Credit program]               []   

      affiliated_organizations  JACK_conviction  \
13009                       []            False   
2951                        []            False   
6166                        []            False   
15976                       []            False   
1266                        []            False   
1267                        []            False   
1268                        []            False   
1269                        []            False   
1270                        []            False   
1271                        []            False   

                                filing_uuid fil

In [ ]:
df_fromamend.iloc[range(k,k+10)]

Looks OK.

Note that of the 541 amendments, 432 modify filings in Q2 2023. The remaining 109 amendments we store as a new dataframe.

In [19]:
rem=pd.concat([dropped_A,df_fromamend]).drop_duplicates(subset=['reg_id','cl_id'],keep=False)

In [20]:
len(rem)

109

We now hunt for where the corresponding files to amend are.

In [21]:
df_Y=clean_cols(pd.read_csv("../../lobbying-local-data/LDA_data/Filings_2023/filings_2023_Q2Y.csv"))
dropped_Y=df_Y.drop_duplicates(subset=['reg_id','cl_id'], keep='last')

In [22]:
rem_to_amend=pd.DataFrame()
rem_from_amend=pd.DataFrame()
for i in range(len(rem)):
    reg_id_to_find=rem.iloc[i]['reg_id']
    cl_id_to_find=rem.iloc[i]['cl_id']
    rem_i=pd.DataFrame(rem.iloc[[i]])
    dropped_Y_i=pd.DataFrame(dropped_Y.loc[(dropped_Y.reg_id==reg_id_to_find) &  (dropped_Y.cl_id==cl_id_to_find)])
    rem_to_amend=pd.concat([rem_to_amend,dropped_Y_i])
    if len(dropped_Y_i)>0:
        rem_from_amend=pd.concat([rem_from_amend, rem_i])

We take a look:

In [23]:
pd.concat([rem_from_amend,rem_to_amend]).sort_values(['reg_id','cl_id'])

registrant  \
521                  APCO WORLDWIDE LLC   
981                  APCO WORLDWIDE LLC   
435                       BRACEWELL LLP   
1851                      BRACEWELL LLP   
366   NATURAL RESOURCES DEFENSE COUNCIL   
1754  NATURAL RESOURCES DEFENSE COUNCIL   
285         CARDINAL INFRASTRUCTURE LLC   
2060        CARDINAL INFRASTRUCTURE LLC   
362                   JILL WARREN, P.C.   
2342                  JILL WARREN, P.C.   
15                      ACT FOR AMERICA   
22                      ACT FOR AMERICA   
131                   HANKA ADVISOR LLC   
1075                  HANKA ADVISOR LLC   
253               PETER DAMON GROUP LLC   
194               PETER DAMON GROUP LLC   

                                           client   income  expenses  \
521                  LIMINEX, INC. DBA GOGUARDIAN  30000.0       0.0   
981                  LIMINEX, INC. DBA GOGUARDIAN      0.0       0.0   
435               DENKA PERFORMANCE ELASTOMER LLC  65000.0       0.0   
1851              DENKA PERFORMANCE ELASTOMER LLC      0.0       0.0   
366             NATURAL RESOURCES DEFENSE COUNCIL      0.0  276960.0   
1754            NATURAL RESOURCES DEFENSE COUNCIL      0.0  276960.0   
285                           THE ROUTING COMPANY      0.0       0.0   
2060                          THE ROUTING COMPANY      0.0       0.0   
362                           ICON AIRCRAFT, INC.      0.0       0.0   
2342                          ICON AIRCRAFT, INC.      0.0       0.0   
15                                ACT FOR AMERICA      0.0    7500.0   
22                                ACT FOR AMERICA      0.0       0.0   
131                    FLAGSHIP ENTERPRISE CENTER      0.0       0.0   
1075                   FLAGSHIP ENTERPRISE CENTER      0.0       0.0   
253   STATE FEDERAL STRATEGIES ON BEHALF OF NCCMP      0.0       0.0   
194   STATE FEDERAL STRATEGIES ON BEHALF OF NCCMP  15000.0       0.0   

          issue_codes                                   entities_lobbied  \
521        [EDU, TEC]                                                 []   
981                []                                                 []   
435        [BUD, CHM]  [Environmental Protection Agency (EPA), HOUSE ...   
1851               []                                                 []   
366   [TAX, GOV, ECN]                 [HOUSE OF REPRESENTATIVES, SENATE]   
1754               []                                                 []   
285        [BUD, TRA]  [Federal Transit Administration (FTA), HOUSE O...   
2060               []                                                 []   
362             [AVI]                                                 []   
2342               []                                                 []   
15              [DEF]                                                 []   
22                 []                                                 []   
131             [ECN]                                                 []   
1075               []                                                 []   
253             [RET]  [HOUSE OF REPRESENTATIVES, Labor, Dept of (DOL...   
194                []                                                 []   

                                   lobbying_description  \
521   [General issues related to ed tech and school ...   
981                                                  []   
435   [Appropriations issues related to Appropriatio...   
1851                                                 []   
366   [Debt Limit - H.R. 415 - IRA defense. IRA defe...   
1754                                                 []   
285   [THUD programmatic appropriations request, Aut...   
2060                                                 []   
362                        [FAA Aircraft Certification]   
2342                                                 []   
15    [HR1725 - END ZUCKERBUCKS ACT - Claudia Tenney...   
22                                                   []   
131   [Consu

This takes care of 8 more. We keep the remaining 101 as a dataframe.

In [25]:
rem_Y=pd.concat([rem,rem_from_amend]).drop_duplicates(subset=['reg_id','cl_id'],keep=False)

In [27]:
df_T=clean_cols(pd.read_csv("../../lobbying-local-data/LDA_data/Filings_2023/filings_2023_2T.csv"))
dropped_T=df_T.drop_duplicates(subset=['reg_id','cl_id'],keep='last')

In [28]:
rem_Y_to_amend=pd.DataFrame()
rem_Y_from_amend=pd.DataFrame()
for i in range(len(rem_Y)):
    reg_id_to_find=rem_Y.iloc[i]['reg_id']
    cl_id_to_find=rem_Y.iloc[i]['cl_id']
    rem_Y_i=pd.DataFrame(rem_Y.iloc[[i]])
    dropped_T_i=pd.DataFrame(dropped_T.loc[(dropped_T.reg_id==reg_id_to_find) &  (dropped_T.cl_id==cl_id_to_find)])
    rem_Y_to_amend=pd.concat([rem_Y_to_amend,dropped_T_i])
    if len(dropped_T_i)>0:
        rem_Y_from_amend=pd.concat([rem_Y_from_amend, rem_Y_i])
pd.concat([rem_Y_from_amend,rem_Y_to_amend]).sort_values(['reg_id','cl_id'])

registrant                    client    income  expenses  \
264  MARIJUANA POLICY PROJECT  MARIJUANA POLICY PROJECT       0.0       0.0   
448  MARIJUANA POLICY PROJECT  MARIJUANA POLICY PROJECT       0.0       0.0   
214       MCLARTY INBOUND LLC       AN ACQUISITION, LLC  130000.0       0.0   
464       MCLARTY INBOUND LLC       AN ACQUISITION, LLC  130000.0       0.0   

    issue_codes                           entities_lobbied  \
264  [AGR, BAN]                 [HOUSE OF REPRESENTATIVES]   
448  [AGR, BAN]                 [HOUSE OF REPRESENTATIVES]   
214       [GOV]  [State, Dept of (DOS), Treasury, Dept of]   
464       [GOV]  [State, Dept of (DOS), Treasury, Dept of]   

                                  lobbying_description foreign_entities  \
264  [H.R.2 - Agriculture Improvement Act of 2018, ...               []   
448  [Made recommended improvements to the Agricult...               []   
214  [To provide advocacy support for the potential...               []   
464  [To provide advocacy support for the potential...               []   

    affiliated_organizations  JACK_conviction  \
264                       []            False   
448                       []            False   
214                       []            False   
464                       []            False   

                              filing_uuid filing_type expenses_method  \
264  8c741c5d-cffe-4a43-8479-bab8a8483ca4          2A               A   
448  97b5db56-a2b5-42f8-be72-aba8f7ad9fc6          2T               A   
214  4c2fdb6c-1cf9-4aec-b5a5-0cee8e27fca5          2A               0   
464  6e2c4002-c394-4dba-bc66-dc191e64783b          2T               0   

                     dt_posted     reg_id   cl_id  
264  2023-07-28T14:27:37-04:00      74330  167449  
448  2023-09-14T21:22:43-04:00      74330  167449  
214  2023-07-20T21:41:46-04:00  401103585   55982  
464  2023-10-19T19:30:36-04:00  401103585   55982

That's 2 more. 99 to go. Let's look at the previous quarters filings, and see if these amendments are meant to apply to them.

In [29]:
rem_YT=pd.concat([rem_Y,rem_Y_from_amend]).drop_duplicates(subset=['reg_id','cl_id'],keep=False)

In [31]:
df_1=clean_cols(pd.read_csv("../../lobbying-local-data/LDA_data/Filings_2023/filings_2023_Q1.csv"))
dropped_1=df_1.drop_duplicates(subset=['reg_id','cl_id'],keep='last')

In [32]:
rem_YT_to_amend=pd.DataFrame()
rem_YT_from_amend=pd.DataFrame()
for i in range(len(rem_YT)):
    reg_id_to_find=rem_YT.iloc[i]['reg_id']
    cl_id_to_find=rem_YT.iloc[i]['cl_id']
    rem_YT_i=pd.DataFrame(rem_YT.iloc[[i]])
    dropped_1_i=pd.DataFrame(dropped_1.loc[(dropped_1.reg_id==reg_id_to_find) &  (dropped_1.cl_id==cl_id_to_find)])
    rem_YT_to_amend=pd.concat([rem_YT_to_amend,dropped_1_i])
    if len(dropped_1_i)>0:
        rem_YT_from_amend=pd.concat([rem_YT_from_amend, rem_YT_i])
pd.concat([rem_YT_from_amend,rem_YT_to_amend]).sort_values(['reg_id','cl_id'])

registrant  \
595                    CREDIT UNION NATIONAL ASSOCIATION   
9756                   CREDIT UNION NATIONAL ASSOCIATION   
219                                     EXXON MOBIL CORP   
15194                                   EXXON MOBIL CORP   
229                                 HOGAN LOVELLS US LLP   
7197                                HOGAN LOVELLS US LLP   
474                                        CLIFF MADISON   
17937                                      CLIFF MADISON   
241       SOCIETY OF CHEMICAL MANUFACTURERS & AFFILIATES   
16688     SOCIETY OF CHEMICAL MANUFACTURERS & AFFILIATES   
585                                    GENESIS GROUP LLC   
18082                                  GENESIS GROUP LLC   
295                          ADVANCED CAPITOL CONSULTING   
18066                        ADVANCED CAPITOL CONSULTING   
296                          ADVANCED CAPITOL CONSULTING   
18067                        ADVANCED CAPITOL CONSULTING   
397                    FRONTLINE PUBLIC STRATEGIES, INC.   
18023                  FRONTLINE PUBLIC STRATEGIES, INC.   
519                                  MR. PETER DICKINSON   
17567                                MR. PETER DICKINSON   
403                                      MR. JAIME STEVE   
17866                                    MR. JAIME STEVE   
404                                      MR. JAIME STEVE   
17635                                    MR. JAIME STEVE   
405                                      MR. JAIME STEVE   
17637                                    MR. JAIME STEVE   
257                                KEY IMPACT STRATEGIES   
18036                              KEY IMPACT STRATEGIES   
79                                         HEALTHSPERIEN   
7893                                       HEALTHSPERIEN   
71                                         HEALTHSPERIEN   
42                                         HEALTHSPERIEN   
73                                         HEALTHSPERIEN   
8479                                       HEALTHSPERIEN   
75                                         HEALTHSPERIEN   
7933                                       HEALTHSPERIEN   
76                                         HEALTHSPERIEN   
7782                                       HEALTHSPERIEN   
77                                         HEALTHSPERIEN   
7902                                       HEALTHSPERIEN   
78                                         HEALTHSPERIEN   
7743                                       HEALTHSPERIEN   
203    OLYMPUS CAPITOL STRATEGIES, LLC (FKA OLYMPUS P...   
17394  OLYMPUS CAPITOL STRATEGIES, LLC (FKA OLYMPUS P...   
119                                   APPALACHIAN VOICES   
17921                                 APPALACHIAN VOICES   
234                                    MS. DANA KUHNLINE   
18058                                  MS. DANA KUHNLINE   

                                                  client   income   expenses  \
595                    CREDIT UNION NATIONAL ASSOCIATION      0.0  1010000.0   
9756                   CREDIT UNION NATIONAL ASSOCIATION      0.0  1030678.0   
219                                     EXXON MOBIL CORP      0.0  1300000.0   
15194                                   EXXON MOBIL CORP      0.0  1600000.0   
229                                        GROWTH ENERGY  60000.0        0.0   
7197                                       GROWTH ENERGY  20000.0        0.0   
474                    NEWHALL LAND AND FARMING COMPANYU  24000.0        0.0   
17937                  NEWHALL LAND AND FARMING COMPANYU  24000.0        0.0   
241       SOCIETY OF CHEMICAL MANUFACTURERS & AFFILIATES      0.0    10000.0   
16688     SOCIETY OF CHEMICAL MANUFACTURERS & AFFILIATES      0.0    10000.0   
585                                     ACE LABORATORIES  10000.0        0.0   
18082                                   ACE LABORATORIES  10000.0        0.0   
295                  AMERICAN COLLEGE OF SPORTS MEDICINE  45000.0

This is extremely unconvincing. More likely, it seems that these 99 filings were meant to be standard Q2 filings, but the "amendment" box on the form accidentally was ticked. In fact, based on this (and some other playing around with the data), I'm going to make a blanket call that amendment filings reference only the quarter in which they are filed.

That's enough exploration.

Let's now formalize what our process looks like for incorporating amendments. First, we will look at the correct place for each amendment type, i.e. for 2A we look at 2, for 2AY we look at 2Y, for 2@ we look at 2T, for 2@Y we look at 2TY. We update 2, 2Y, 2T, 2TY accordingly (we can do this by e.g. concatenating 2 and the matching filings in 2A, then dropping duplicates keeping the first). There will be leftovers, which I call `rem_A`, `rem_AY`, `rem_@`, `rem_@Y`. From these, we make a full collection of remainders `rem_all` by concatenating `rem_A`, `rem_AY`, `rem_@`, `rem_@Y` and dropping duplicates. Finally, we look at the unmatched filings in 2, 2Y, 2T, 2TY, which I call `unmatch`, `unmatch_Y`, `unmatch_T`, `unmatch_TY`, concatenate and drop duplicates to get `unmatch_all`, then search `unmatch_all` for filings in `rem_all` and replace. What is left over I will call `true_rem`, and simply add it to the dataframe.

In [62]:
filing_suffixes=['','Y','T','TY']
amendment_suffixes=['A','AY','@', '@Y']
fil_2_am=dict(zip(filing_suffixes,amendment_suffixes))


relevant_filing_types=["Q1","Q1Y","1T","1TY","1A","1AY","1@","1@Y","Q2","Q2Y","2T","2TY","2A","2AY","2@","2@Y","Q3","Q3Y","3T","3TY","3A","3AY","3@","3@Y","Q4","Q4Y","4T","4TY","4A","4AY","4@","4@Y"]
stand_filing_types=["1","1Y","1T","1TY","1A","1AY","1@","1@Y","2","2Y","2T","2TY","2A","2AY","2@","2@Y","3","3Y","3T","3TY","3A","3AY","3@","3@Y","4","4Y","4T","4TY","4A","4AY","4@","4@Y"]
rel_2_stand=dict(zip(relevant_filing_types, stand_filing_types))
stand_2_rel=dict(zip(stand_filing_types, relevant_filing_types))

quarter=2
year=2023
rem_all=pd.DataFrame() #empty dataframe to start, will add to it
filing_all=pd.DataFrame() #empty dataframe to start, will add to it
for suff in filing_suffixes:
    filing=clean_cols(pd.read_csv("../../lobbying-local-data/LDA_data/Filings_"+str(year)+"/filings_"+str(year)+"_"+stand_2_rel[str(quarter)+suff]+".csv")).drop_duplicates(subset=['reg_id','cl_id'],keep='last') #loading in filings, dropping duplicates keeping most recent
    filing_am=clean_cols(pd.read_csv("../../lobbying-local-data/LDA_data/Filings_"+str(year)+"/filings_"+str(year)+"_"+stand_2_rel[str(quarter)+fil_2_am[suff]]+".csv")).drop_duplicates(subset=['reg_id','cl_id'],keep='last') # same for amendments
    rem=pd.concat([filing_am, filing, filing]).drop_duplicates(subset=['reg_id','cl_id'],keep=False) #gives all amendments with no matching filing, corresponds to rem_A, etc in discussion above
    filing_am_matched=pd.concat([filing_am,rem]).drop_duplicates(subset=['reg_id','cl_id'],keep=False) #gives all matched amendments
    filing=pd.concat([filing, filing_am_matched]).drop_duplicates(subset=['reg_id','cl_id'],keep='last') #updates filing with the matched amendments.
    rem_all=pd.concat([rem_all, rem]).drop_duplicates(subset=['reg_id','cl_id'],keep='first') #adds rem to rem_all, tossing repeats
    filing_all=pd.concat([filing_all, filing]).drop_duplicates(subset=['reg_id','cl_id'],keep='first')
filing_all.sort_values('dt_posted',axis=0)
rem_all.sort_values('dt_posted',axis=0)
final_filing=pd.concat([filing_all, rem_all]).drop_duplicates(subset=['reg_id','cl_id'],keep='last').sort_values('dt_posted',axis=0) #this replaces entries in filing_all that match something in rem_all, and appends the leftovers (true_rem) to the dataframe

In [143]:
final_filing.head()

registrant  \
0  SARAH BLACKWOOD GOVERNMENT RELATIONS, LLC   
0                          ROSETTA GROUP LLC   
1                   PARDES BIOSCIENCES, INC.   
0                  CONTINENTAL STRATEGY, LLC   
1                 EDENRED NORTH AMERICA INC.   

                                              client    income  expenses  \
0                                       NOVELIS INC.   20000.0       0.0   
0  CORMAC GROUP ON BEHALF OF NOVA SOUTHEASTERN UN...   10000.0       0.0   
1                           PARDES BIOSCIENCES, INC.       0.0  120000.0   
0                          TETHER OPERATIONS LIMITED  150000.0       0.0   
1                         EDENRED NORTH AMERICA INC.       0.0       0.0   

            issue_codes                                   entities_lobbied  \
0                    []                                                 []   
0                 [EDU]                 [HOUSE OF REPRESENTATIVES, SENATE]   
1  [MED, MMM, PHA, HCR]  [Centers For Medicare and Medicaid Services (C...   
0                 [BAN]                                                 []   
1                    []                                                 []   

                                lobbying_description foreign_entities  \
0                                                 []               []   
0                         [Labor HHS appropriations]               []   
1  [NIH funding for clinical trials, Medicare cov...               []   
0               [Legislation related to stablecoins]               []   
1                                                 []               []   

  affiliated_organizations  JACK_conviction  \
0                       []            False   
0                       []            False   
1                       []            False   
0                       []            False   
1                       []            False   

                            filing_uuid filing_type expenses_method  \
0  3bbf137f-98d2-47d5-ad28-8c39affab1e0         2TY               0   
0  6f0fec31-f304-4e34-8e1e-350cdbcb1bd1          2T               0   
1  7b178cfd-76ff-4ab0-bfa0-f3bee1a34931          2T               A   
0  e910f68a-0285-4caf-8408-b32716fe7070          Q2               0   
1  34e52f19-185e-4b48-b39e-473d6e6ea34c         2TY               A   

             dt_posted     reg_id   cl_id  
0  2023-04-03T16:23:26  401103935  200384  
0  2023-04-11T16:40:13  401106009  210139  
1  2023-04-12T10:26:43  401106493   45950  
0  2023-04-17T13:52:00  401106285   54177  
1  2023-04-17T17:15:15  401106600   51333

Let's make this a function.

In [65]:
def update_filings(quarter, year):
    filing_suffixes=['','Y','T','TY']
    amendment_suffixes=['A','AY','@', '@Y']
    fil_2_am=dict(zip(filing_suffixes,amendment_suffixes))
    relevant_filing_types=["Q1","Q1Y","1T","1TY","1A","1AY","1@","1@Y","Q2","Q2Y","2T","2TY","2A","2AY","2@","2@Y","Q3","Q3Y","3T","3TY","3A","3AY","3@","3@Y","Q4","Q4Y","4T","4TY","4A","4AY","4@","4@Y"]
    stand_filing_types=["1","1Y","1T","1TY","1A","1AY","1@","1@Y","2","2Y","2T","2TY","2A","2AY","2@","2@Y","3","3Y","3T","3TY","3A","3AY","3@","3@Y","4","4Y","4T","4TY","4A","4AY","4@","4@Y"]
    rel_2_stand=dict(zip(relevant_filing_types, stand_filing_types))
    stand_2_rel=dict(zip(stand_filing_types, relevant_filing_types))

    rem_all=pd.DataFrame() #empty dataframe to start, will add to it
    filing_all=pd.DataFrame() #empty dataframe to start, will add to it
    for suff in filing_suffixes:
        filing=clean_cols(pd.read_csv("../../lobbying-local-data/LDA_data/Filings_"+str(year)+"/filings_"+str(year)+"_"+stand_2_rel[str(quarter)+suff]+".csv")).drop_duplicates(subset=['reg_id','cl_id'],keep='last') #loading in filings, dropping duplicates keeping most recent
        filing_am=clean_cols(pd.read_csv("../../lobbying-local-data/LDA_data/Filings_"+str(year)+"/filings_"+str(year)+"_"+stand_2_rel[str(quarter)+fil_2_am[suff]]+".csv")).drop_duplicates(subset=['reg_id','cl_id'],keep='last') # same for amendments
        rem=pd.concat([filing_am, filing, filing]).drop_duplicates(subset=['reg_id','cl_id'],keep=False) #gives all amendments with no matching filing, corresponds to rem_A, etc in discussion above
        filing_am_matched=pd.concat([filing_am,rem]).drop_duplicates(subset=['reg_id','cl_id'],keep=False) #gives all matched amendments
        filing=pd.concat([filing, filing_am_matched]).drop_duplicates(subset=['reg_id','cl_id'],keep='last') #updates filing with the matched amendments.
        rem_all=pd.concat([rem_all, rem]).drop_duplicates(subset=['reg_id','cl_id'],keep='first') #adds rem to rem_all, tossing repeats
        filing_all=pd.concat([filing_all, filing]).drop_duplicates(subset=['reg_id','cl_id'],keep='first')
    filing_all.sort_values('dt_posted',axis=0)
    rem_all.sort_values('dt_posted',axis=0)
    updated_filings=pd.concat([filing_all, rem_all]).drop_duplicates(subset=['reg_id','cl_id'],keep='last').sort_values('dt_posted',axis=0) #this replaces entries in filing_all that match something in rem_all, and appends the leftovers (true_rem) to the dataframe
    updated_filings=updated_filings.drop(labels=['dt_posted'], axis=1)
    return updated_filings

## (5) Dealing with `incomes` and `expenses`.

We now have to figure out what to do when we are unsure about whether the filing should have `income` or `expenses`. First, we repeat a sanity check.

In [9]:
final_filing.loc[(final_filing.income!=0) & (final_filing.expenses!=0)]

Empty DataFrame
Columns: [registrant, client, income, expenses, issue_codes, entities_lobbied, lobbying_description, foreign_entities, affiliated_organizations, JACK_conviction, filing_uuid, filing_type, expenses_method, dt_posted, reg_id, cl_id]
Index: []

We are actually worried about the other extreme - when both `income` and `expenses` are not reported.

In [10]:
final_filing.loc[(final_filing.income==0) & (final_filing.expenses==0)]

registrant  \
1                           EDENRED NORTH AMERICA INC.   
2                                  BLUEBIRD STRATEGIES   
3                                CAPITAL HEALTH SYSTEM   
4                 COMMONWEALTH STRATEGIC PARTNERS, LLC   
5                 COMMONWEALTH STRATEGIC PARTNERS, LLC   
...                                                ...   
2383                             JON THOMAS CONSULTING   
61    INTERNATIONAL ASSOCATION OF DRILLING CONTRACTORS   
2384                                    TRADEWINS, LLC   
2385                           MCALLISTER & QUINN, LLC   
2386                            TERRAPIN STRATEGY INC.   

                                                 client  income  expenses  \
1                            EDENRED NORTH AMERICA INC.     0.0       0.0   
2                                     PEAR THERAPEUTICS     0.0       0.0   
3                                 CAPITAL HEALTH SYSTEM     0.0       0.0   
4                                                 SHIPT     0.0       0.0   
5       PENNSYLVANIA ASSISTED LIVING ASSOCIATION (PALA)     0.0       0.0   
...                                                 ...     ...       ...   
2383                             LETS GO BOYS AND GIRLS     0.0       0.0   
61    INTERNATIONAL ASSOCIATION OF DRILLING CONTRACTORS     0.0       0.0   
2384  HOGAN LOVELLS US LLP (ON BEHALF OF BECTON DICK...     0.0       0.0   
2385                                   LYCOMING COLLEGE     0.0       0.0   
2386                                    BELEN AEROSPACE     0.0       0.0   

     issue_codes entities_lobbied lobbying_description foreign_entities  \
1             []               []                   []               []   
2             []               []                   []               []   
3             []               []                   []               []   
4             []               []                   []               []   
5             []               []                   []               []   
...          ...              ...                  ...              ...   
2383          []               []                   []               []   
61            []               []                   []               []   
2384          []               []                   []               []   
2385          []               []                   []               []   
2386          []               []                   []               []   

     affiliated_organizations  JACK_conviction  \
1                          []            False   
2                          []            False   
3                          []            False   
4                          []            False   
5                          []            False   
...                       ...              ...   
2383                       []            False   
61                         []            False   
2384                       []            False   
2385                       []            False   
2386                       []            False   

                               filing_uuid filing_type expenses_method  \
1     34e52f19-185e-4b48-b39e-473d6e6ea34c         2TY               A   
2     fc8fc80e-7181-4a8d-94ee-dedf5f403dc3         2TY               0   
3     dd4fdacb-85b1-466a-ae4e-cc0a2e3f05a4         2TY               A   
4     55995714-96bf-4350-85cd-ead081776b03         2TY               0   
5     292d5082-fe11-4bc2-83f9-020816f4c92e         2TY               0   
...                                    ...         ...             ...   
2383  9049ed18-0cb2-49ef-89c9-8fc4bbacb56e         Q2Y               0   
61    deb50ef4-9275-43f7-958d-5bf3bad55935         2AY               0   
2384  380e73ab-c303-4f77-9547-a7a0415e8587         Q2Y               0   
2385  d6bce7fb-0c66-400c-a283-d86c82bb0ff4         Q2Y               0   
2386  6f65e201-20e8-4c99-a839-c2db40874af0         Q2Y               0   

               dt_posted     re

We can try to identify which of these are `expenses` by looking at when the registrant is the client. For this, we need to remove junk from the registrant and client columns.

In [11]:
def strip_stop(sentence):
    stop_words = set(stopwords.words('english')+list(punctuation))
    word_tokens = word_tokenize(sentence) # converts the words in word_tokens to lower case and then checks whether they are present in stop_words or not
    filtered_sentence = [w.lower() for w in word_tokens if not w.lower() in stop_words] #with lower case conversion
    filtered_string=""
    for w in filtered_sentence:
        filtered_string=filtered_string+w
    return filtered_string

In [45]:
reg_stripped=[strip_stop(final_filing.iloc[j]['registrant']) for j in range(len(final_filing))]
cl_stripped=[strip_stop(final_filing.iloc[j]['client']) for j in range(len(final_filing))]
final_filing['reg_stripped']=reg_stripped
final_filing['cl_stripped']=cl_stripped


In [13]:
name_and_method=final_filing.loc[(final_filing.reg_stripped == final_filing.cl_stripped) & (final_filing.expenses_method !=0)]
method=final_filing.loc[ (final_filing.expenses_method !=0)]
name=final_filing.loc[(final_filing.reg_stripped == final_filing.cl_stripped)]

In [19]:
name_not_method=pd.concat([name, name_and_method]).drop_duplicates(subset=['reg_id','cl_id'],keep=False)
method_not_name=pd.concat([method, name_and_method]).drop_duplicates(subset=['reg_id','cl_id'],keep=False)

In [22]:
name_not_method

registrant  \
6                                     HOME INSTEAD, INC.   
95        CLERGY FINANCIAL STRATEGY AND TAX PLANNING INC   
589                                    ENDOCRINE SOCIETY   
843                       CHAMBER OF SHIPPING OF AMERICA   
14                                           SLEEP, INC.   
1068   PROTON THERAPY CONSORTIUM FKA NATIONAL ASSOCIA...   
177          CENTER FOR ARMS CONTROL & NON-PROLIFERATION   
1105                         COUNCIL FOR A LIVABLE WORLD   
1116   AMERICAN SOCIETY FOR BIOCHEMISTRY AND MOLECULA...   
215          JUVENILE PRODUCTS MANUFACTURERS ASSOCIATION   
1526        NATIONAL ASSOCIATION OF SCHOOL PSYCHOLOGISTS   
1551                    FREEDOM FROM RELIGION FOUNDATION   
1918                       ULTRA ELECTRONICS DEFENSE INC   
4860            CONSUMER HEALTHCARE PRODUCTS ASSOCIATION   
5101   INDUSTRY COUNCIL FOR EMERGENCY RESPONSE TECHNO...   
6598                            NEOGENOMICS LABORATORIES   
6832                        OCEAN SPRAY CRANBERRIES, INC   
7538           ELECTRIC DRIVE TRANSPORTATION ASSOCIATION   
9418                         RAILS-TO-TRAILS CONSERVANCY   
1519                                 AG PROCESSING, INC.   
12384           AMERICAN ISRAEL PUBLIC AFFAIRS COMMITTEE   
1615                                  FOOD & WATER WATCH   
15011                   HEMOPHILIA FEDERATION OF AMERICA   
15399                               PUBLIC LANDS COUNCIL   
15531                          UNITED SPINAL ASSOCIATION   
15600  THE NATIONAL GRANGE OF THE ORDER OF PATRONS OF...   
1842                  ANAKLIA DEVELOPMENT CONSORTIUM LLC   
16861  COALITION FOR AMERICA'S GATEWAYS & TRADE CORRI...   
16882                          ELK CREEK RESOURCES CORP.   
16893           UNIVERSITY OF MISSISSIPPI MEDICAL CENTER   
17338              NATIONAL EMERGENCY NUMBER ASSOCIATION   
292                               THE CAVALRY GROUP, LLC   
2088                                       SOMATUS, INC.   
17535                                    YMCA OF THE USA   
17767      INTERNATIONAL MOTOR VEHICLE TRADE ASSOCIATION   
17957                    CALIFORNIA FORESTRY ASSOCIATION   
2336                          AFRICAN FEDERAL GROUP, LLC   
18156  NATIONAL COUNCIL FOR LANGUAGES AND INTERNATION...   
18172            ALTERNATIVE FUELS & CHEMICALS COALITION   
2353                                ANDERSON & CALLENDER   
18201                            CHRISTIAN LEGAL SOCIETY   
2365                           ALBANIAN AMERICAN COUNCIL   
541                                      HNI CORPORATION   
18334                           CYPRESS CREEK RENEWABLES   

                                                  client    income  expenses  \
6                                     HOME INSTEAD, INC.   75000.0       0.0   
95        CLERGY FINANCIAL STRATEGY AND TAX PLANNING INC       0.0       0.0   
589                                    ENDOCRINE SOCIETY       0.0       0.0   
843                       CHAMBER OF SHIPPING OF AMERICA       0.0       0.0   
14                                           SLEEP, INC.       0.0       0.0   
1068   PROTON THERAPY CONSORTIUM FKA NATIONAL ASSOCIA...       0.0       0.0   
177          CENTER FOR ARMS CONTROL & NON-PROLIFERATION       0.0       0.0   
1105                         COUNCIL FOR A LIVABLE WORLD   40000.0       0.0   
1116   AMERICAN SOCIETY FOR BIOCHEMISTRY AND MOLECULA...    5000.0       0.0   
215          JUVENILE PRODUCTS MANUFACTURERS ASSOCIATION       0.0       0.0   
1526        NATIONAL ASSOCIATION OF SCHOOL PSYCHOLOGISTS   10000.0       0.0   
1551                    FREEDOM FROM RELIGION FOUNDATION   50000.0       0.0   
1918                      ULTRA ELECTRONICS DEFENSE INC.  120000.0       0.0   
4860            CONSUMER HEALTHCARE PRODUCTS ASSOCIATION  171093.0       0.0   
5101   INDUSTRY COUNCIL FOR EMERGENCY RESPONSE TECHNO...   15000.0       0.0   
6598                            NEOGENOMICS LABORATORIES   60000.

In [27]:
name_not_method.loc[name_not_method['expenses']!=0]

Empty DataFrame
Columns: [registrant, client, income, expenses, issue_codes, entities_lobbied, lobbying_description, foreign_entities, affiliated_organizations, JACK_conviction, filing_uuid, filing_type, expenses_method, dt_posted, reg_id, cl_id, reg_stripped, cl_stripped]
Index: []

These `name_not_method`-filings all appear to be `expense`-type filings, but with errors in paperwork. It looks like they entered under `income` sometimes when they should have entered under `expenses`.

In [25]:
method_not_name.sample(10)

registrant  \
17168  NATIONAL COOPERATIVE BANK, N.A. (FORMERLY NCB,...   
9562                                 SOUNDEXCHANGE, INC.   
11915  KOCH GOVERNMENT AFFAIRS, LLC (FORMERLY KNOWN A...   
1955                                     STEPHEN BASSETT   
5702   LIVE OAK BANKING COMPANY (FORMERLY KNOWN AS LI...   
16589            ADISA - ALTERNATIVE & DIRECT INVESTMENT   
8768   ASTELLAS GENE THERAPIES, INC. A DELAWARE CORPO...   
587              NATIONAL EMPLOYMENT LAWYERS ASSOCIATION   
2108   A.C.E. CONSULTING DBA A.C.E. CONSTRUCTION CONS...   
14368             AT&T SERVICES, INC. AND ITS AFFILIATES   

                                                  client  income   expenses  \
17168                                           NCB, FSB     0.0    35000.0   
9562                                       SOUNDEXCHANGE     0.0   240000.0   
11915  KOCH GOVERNMENT AFFAIRS, LLC (FORMERLY KNOWN A...     0.0  2020000.0   
1955   PARADIGM RESEARCH GROUP (FORMALLY KNOWN AS STE...     0.0        0.0   
5702                                       LIVE OAK BANK     0.0   110000.0   
16589  ALTERNATIVE & DIRECT INVESTMENT SECURITIES ASS...     0.0   114133.0   
8768   ASTELLAS GENE THERAPIES, INC. A DELAWARE CORPO...     0.0    90000.0   
587       NATIONAL EMPLOYMENT LAWYERS ASSOCIATION (NELA)     0.0    20000.0   
2108                                   A.C.E. CONSULTING     0.0        0.0   
14368               AT&T SERVICES INC AND ITS AFFILIATES     0.0  2780000.0   

                                             issue_codes  \
17168                                              [SMB]   
9562                                               [CPT]   
11915  [TEC, AGR, BNK, UTI, CHM, TRD, TRA, TAX, LAW, ...   
1955                                                  []   
5702                                [AGR, SMB, BUD, BAN]   
16589                               [ENV, TAX, ACC, BUD]   
8768                                          [HCR, MMM]   
587                                           [CIV, LBR]   
2108                                                  []   
14368                                    [TRD, TAX, TEC]   

                                        entities_lobbied  \
17168                 [HOUSE OF REPRESENTATIVES, SENATE]   
9562                  [HOUSE OF REPRESENTATIVES, SENATE]   
11915                 [HOUSE OF REPRESENTATIVES, SENATE]   
1955                                                  []   
5702   [Agriculture, Dept of (USDA), Federal Deposit ...   
16589                         [HOUSE OF REPRESENTATIVES]   
8768                  [HOUSE OF REPRESENTATIVES, SENATE]   
587    [Equal Employment Opportunity Commission (EEOC...   
2108                                                  []   
14368  [Commerce, Dept of (DOC), Federal Aviation Adm...   

                                    lobbying_description foreign_entities  \
17168  [Cooperative business eligibility for SBA lend...               []   
9562   [Music copyright issues; American Music Fairne...               []   
11915  [General issues relating to spectrum reauthori...               []   
1955                                                  []               []   
5702   [- Issues related to 2023 Farm bill, including...               []   
16589  [ESG report requirement, Fiduciary rule, Accre...               []   
8768   [Value of Prescription Drugs, Drug pricing, Bi...               []   
587    [trengthening of laws against sexual and workp...               []   
2108                                                  []               []   
14368  [issues related to the enforcement of USMCA, S...               []   

      affiliated_organizations  JACK_conviction  \
17168                       []            False   
9562                        []            False   
11915                       []            False   
1955                        []            False   
5702                        []            False   
16589                       []         

These `method_not_name` entries all appear to be true `expense`-type filings.

So we should look for all filings which either have matching registrant-client entires, or have non-zero entries in `expenses_method`. These are all of the true `expense`-type filings.

In [55]:
expense_type=final_filing.loc[(final_filing.reg_stripped == final_filing.cl_stripped) | (final_filing.expenses_method !=0)].copy()
income_type=pd.concat([final_filing, expense_type]).drop_duplicates(subset=['reg_id','cl_id'], keep=False)

In [56]:
exp_sp=expense_type['expenses']+expense_type['income']
expense_type['expenses']=exp_sp
expense_type['income']=float(0)
inc_sp=income_type['expenses']+income_type['income']
income_type['income']=inc_sp
income_type['expenses']=float(0)

In [57]:
expense_type.loc[expense_type.expenses==0, 'expenses']=float(1)
income_type.loc[income_type.income==0, 'income']=float(1)

In [58]:
expense_type

registrant  \
1                           PARDES BIOSCIENCES, INC.   
1                         EDENRED NORTH AMERICA INC.   
3                              CAPITAL HEALTH SYSTEM   
2                                      CROSSFIT, LLC   
14          INTERNATIONAL SLEEP PRODUCTS ASSOCIATION   
...                                              ...   
2380                           ALECTA STRATEGIES LLC   
18351  THE AMERICAN COUNCIL OF ENGINEERING COMPANIES   
600                                           BIOGEN   
601              THE AMERICAN PUBLIC GAS ASSOCIATION   
18360    DISABILITY RIGHTS EDUCATION & DEFENSE, INC.   

                                          client  income  expenses  \
1                       PARDES BIOSCIENCES, INC.     0.0  120000.0   
1                     EDENRED NORTH AMERICA INC.     0.0       1.0   
3                          CAPITAL HEALTH SYSTEM     0.0       1.0   
2                                  CROSSFIT, LLC     0.0   40000.0   
14      INTERNATIONAL SLEEP PRODUCTS ASSOCIATION     0.0       1.0   
...                                          ...     ...       ...   
2380                       ALECTA STRATEGIES LLC     0.0       1.0   
18351  AMERICAN COUNCIL OF ENGINEERING COMPANIES     0.0  987181.0   
600                                       BIOGEN     0.0  830000.0   
601              AMERICAN PUBLIC GAS ASSOCIATION     0.0   10000.0   
18360  DISABILITY RIGHTS EDUCATION & DEFENSE INC     0.0   10000.0   

                                             issue_codes  \
1                                   [MED, MMM, PHA, HCR]   
1                                                     []   
3                                                     []   
2                                                  [HCR]   
14                                                    []   
...                                                  ...   
2380                                                  []   
18351  [ENV, LBR, FOR, FIN, TRA, TOR, TAX, ROD, IMM, ...   
600                  [CPT, BUD, TRD, TAX, PHA, MMM, HCR]   
601                                                [FUE]   
18360                                    [ECN, CIV, HCR]   

                                        entities_lobbied  \
1      [Centers For Medicare and Medicaid Services (C...   
1                                                     []   
3                                                     []   
2                     [HOUSE OF REPRESENTATIVES, SENATE]   
14                                                    []   
...                                                  ...   
2380                                                  []   
18351  [Army, Dept of (Corps of Engineers), Commerce,...   
600    [Centers For Medicare and Medicaid Services (C...   
601                   [HOUSE OF REPRESENTATIVES, SENATE]   
18360  [Food & Drug Administration (FDA), HOUSE OF RE...   

                                    lobbying_description foreign_entities  \
1      [NIH funding for clinical trials, Medicare cov...               []   
1                                                     []               []   
3                                                     []               []   
2      [Advocating for fitness facilities to be desig...               []   
14                                                    []               []   
...                                                  ...              ...   
2380                                                  []               []   
18351  [Funding for Superfund and other hazardous was...               []   
600    [Support stronger IP and exclusivity protectio...               []   
601    [Amend Section 5 of the Natural Gas Act and pr...               []   
18360  [Recommendations to improve the Supplemental N...               []   

      affiliated_organizations  JACK_conviction  \
1                           []            False   
1                           []            False   
3       

In [51]:
income_type

registrant  \
0              SARAH BLACKWOOD GOVERNMENT RELATIONS, LLC   
0                                      ROSETTA GROUP LLC   
0                              CONTINENTAL STRATEGY, LLC   
2                                    BLUEBIRD STRATEGIES   
4                   COMMONWEALTH STRATEGIC PARTNERS, LLC   
...                                                  ...   
606    TORREY ADVISORY GROUP (FORMERLY MICHAEL TORREY...   
607    TORREY ADVISORY GROUP (FORMERLY MICHAEL TORREY...   
2385                             MCALLISTER & QUINN, LLC   
2386                              TERRAPIN STRATEGY INC.   
18361                           CONLON PUBLIC STRATEGIES   

                                                  client    income  expenses  \
0                                           NOVELIS INC.   20000.0       1.0   
0      CORMAC GROUP ON BEHALF OF NOVA SOUTHEASTERN UN...   10000.0       1.0   
0                              TETHER OPERATIONS LIMITED  150000.0       1.0   
2                                      PEAR THERAPEUTICS       0.0       1.0   
4                                                  SHIPT       0.0       1.0   
...                                                  ...       ...       ...   
606                         ILLINOIS SOYBEAN ASSOCIATION   70000.0       1.0   
607     NATURAL RESOURCES DEFENSE COUNCIL AND AFFILIATES   60000.0       1.0   
2385                                    LYCOMING COLLEGE       0.0       1.0   
2386                                     BELEN AEROSPACE       0.0       1.0   
18361                                               TASC   20000.0       1.0   

           issue_codes                                   entities_lobbied  \
0                   []                                                 []   
0                [EDU]                 [HOUSE OF REPRESENTATIVES, SENATE]   
0                [BAN]                                                 []   
2                   []                                                 []   
4                   []                                                 []   
...                ...                                                ...   
606    [TRA, TRD, AGR]  [Agriculture, Dept of (USDA), HOUSE OF REPRESE...   
607         [FOO, AGR]  [Agriculture, Dept of (USDA), HOUSE OF REPRESE...   
2385                []                                                 []   
2386                []                                                 []   
18361       [HCR, LAW]  [Executive Office of the President (EOP), HOUS...   

                                    lobbying_description foreign_entities  \
0                                                     []               []   
0                             [Labor HHS appropriations]               []   
0                   [Legislation related to stablecoins]               []   
2                                                     []               []   
4                                                     []               []   
...                                                  ...              ...   
606    [Funding for locks and dams. Issues relating t...               []   
607    [Food Date Labeling., Issues in Farm Bill rela...               []   
2385                                                  []               []   
2386                                                  []               []   
18361  [explore grant opportunities and discuss TASC'...               []   

      affiliated_organizations  JACK_conviction  \
0                           []            False   
0                           []            False   
0                           []            False   
2                           []            False   
4                           []            False   
...                        ...              ...   
606                         []            False   
607                         []            False   
2385                        []            False   
2386

In [59]:
ultimate_filing=pd.concat([income_type,expense_type]).sort_values('dt_posted')

In [60]:
ultimate_filing

registrant  \
0              SARAH BLACKWOOD GOVERNMENT RELATIONS, LLC   
0                                      ROSETTA GROUP LLC   
1                               PARDES BIOSCIENCES, INC.   
0                              CONTINENTAL STRATEGY, LLC   
1                             EDENRED NORTH AMERICA INC.   
...                                                  ...   
607    TORREY ADVISORY GROUP (FORMERLY MICHAEL TORREY...   
2385                             MCALLISTER & QUINN, LLC   
18360        DISABILITY RIGHTS EDUCATION & DEFENSE, INC.   
2386                              TERRAPIN STRATEGY INC.   
18361                           CONLON PUBLIC STRATEGIES   

                                                  client    income  expenses  \
0                                           NOVELIS INC.   20000.0       0.0   
0      CORMAC GROUP ON BEHALF OF NOVA SOUTHEASTERN UN...   10000.0       0.0   
1                               PARDES BIOSCIENCES, INC.       0.0  120000.0   
0                              TETHER OPERATIONS LIMITED  150000.0       0.0   
1                             EDENRED NORTH AMERICA INC.       0.0       1.0   
...                                                  ...       ...       ...   
607     NATURAL RESOURCES DEFENSE COUNCIL AND AFFILIATES   60000.0       0.0   
2385                                    LYCOMING COLLEGE       1.0       0.0   
18360          DISABILITY RIGHTS EDUCATION & DEFENSE INC       0.0   10000.0   
2386                                     BELEN AEROSPACE       1.0       0.0   
18361                                               TASC   20000.0       0.0   

                issue_codes  \
0                        []   
0                     [EDU]   
1      [MED, MMM, PHA, HCR]   
0                     [BAN]   
1                        []   
...                     ...   
607              [FOO, AGR]   
2385                     []   
18360       [ECN, CIV, HCR]   
2386                     []   
18361            [HCR, LAW]   

                                        entities_lobbied  \
0                                                     []   
0                     [HOUSE OF REPRESENTATIVES, SENATE]   
1      [Centers For Medicare and Medicaid Services (C...   
0                                                     []   
1                                                     []   
...                                                  ...   
607    [Agriculture, Dept of (USDA), HOUSE OF REPRESE...   
2385                                                  []   
18360  [Food & Drug Administration (FDA), HOUSE OF RE...   
2386                                                  []   
18361  [Executive Office of the President (EOP), HOUS...   

                                    lobbying_description foreign_entities  \
0                                                     []               []   
0                             [Labor HHS appropriations]               []   
1      [NIH funding for clinical trials, Medicare cov...               []   
0                   [Legislation related to stablecoins]               []   
1                                                     []               []   
...                                                  ...              ...   
607    [Food Date Labeling., Issues in Farm Bill rela...               []   
2385                                                  []               []   
18360  [Recommendations to improve the Supplemental N...               []   
2386                                                  []               []   
18361  [explore grant opportunities and discuss TASC'...               []   

      affiliated_organizations  JACK_conviction  \
0                           []            False   
0                           []            False   
1                           []            False   
0                           []            False   
1                           []            False   
...                        ...         

We assemble this into a function.

In [61]:
def strip_stop(sentence):
    stop_words = set(stopwords.words('english')+list(punctuation))
    word_tokens = word_tokenize(sentence) # converts the words in word_tokens to lower case and then checks whether they are present in stop_words or not
    filtered_sentence = [w.lower() for w in word_tokens if not w.lower() in stop_words] #with lower case conversion
    filtered_string=""
    for w in filtered_sentence:
        filtered_string=filtered_string+w
    return filtered_string

def inc_exp(df):
    reg_stripped=[strip_stop(df.iloc[j]['registrant']) for j in range(len(df))]
    cl_stripped=[strip_stop(df.iloc[j]['client']) for j in range(len(df))]
    df['reg_stripped']=reg_stripped
    df['cl_stripped']=cl_stripped
    expense_type=df.loc[(df.reg_stripped == df.cl_stripped) | (df.expenses_method !=0)].copy()
    income_type=pd.concat([df, expense_type]).drop_duplicates(subset=['reg_id','cl_id'], keep=False)
    exp_sp=expense_type['expenses']+expense_type['income']
    expense_type['expenses']=exp_sp
    expense_type['income']=float(0)
    inc_sp=income_type['expenses']+income_type['income']
    income_type['income']=inc_sp
    income_type['expenses']=float(0)
    expense_type.loc[expense_type.expenses==0, 'expenses']=float(1)
    income_type.loc[income_type.income==0, 'income']=float(1)
    ult_df=pd.concat([income_type,expense_type]).sort_values('dt_posted')
    ult_df=ult_df.drop(labels=['reg_stripped','cl_stripped'], axis=1)
    return ult_df
    

## Exporting

We can now clean all of our data and export.

In [ ]:
quarters=range(1,5)
years=range(2013,2025)
for y in years:
    for q in quarters:
        df=update_filings(q,y)
        with inc_exp(df)